SELECT COUNT(*) FROM SALES
--Kaç satýr olduðunu count komutuyla elde ettik.

SELECT * FROM SALES ORDER BY AMOUNT
--Adet sýralamasý yaptýk.En az alan ve en çok alan deðerler.

SELECT MIN(AMOUNT),MAX(AMOUNT) FROM SALES
--En az ve en çok alan deðerleri getirdik.

SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(*) FROM SALES

SELECT SUM(AMOUNT) FROM SALES
--Toplam satýþ adedi.

SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(*),SUM(AMOUNT),AVG(AMOUNT) FROM SALES

SELECT AVG(AMOUNT) FROM SALES
--Ortalama satýþ miktarýný elde ettik.

SELECT * FROM SALES ORDER BY TOTALPRICE

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(*),
SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(*),
SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES WHERE CITY='ADANA'
--Adana için toplam fiyat deðerlerini getirdik.

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(*),
SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES WHERE CITY='ÝSTANBUL'
