SELECT COUNT(*) FROM SALES
--Kaç satýr olduðunu count komutuyla elde ettik.

SELECT * FROM SALES ORDER BY AMOUNT

SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(*),SUM(AMOUNT),AVG(AMOUNT) FROM SALES
--Burada satýlan ürünlerin en az kaç adet, en çok kaç adet, satýr sayýsýný, 
--toplam kaç adet ürün satmýþýz, ortalama satýþ adedi miktarýný bulduk.

SELECT * FROM SALES ORDER BY TOTALPRICE

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(*),SUM(TOTALPRICE),AVG(TOTALPRICE)
FROM SALES

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(*),SUM(TOTALPRICE),AVG(TOTALPRICE)
FROM SALES WHERE CITY = 'ADANA'
--Adana için deðerleri elde ettik.

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(*),SUM(TOTALPRICE),AVG(TOTALPRICE)
FROM SALES WHERE CITY = 'ANKARA'

SELECT CITY,
MIN(TOTALPRICE) AS MINPRICE,MAX(TOTALPRICE) AS MAXPRICE,
COUNT(*) AS ROWCOUNT_,SUM(TOTALPRICE) TOTALPRICE,AVG(TOTALPRICE) AS AVGPRICE
FROM SALES
GROUP BY CITY
--Bu GROUP BY yöntemiyle þehirlere göre bütün deðerleri grupladýk ve tekilleþtirdik.

SELECT CITY,
MIN(TOTALPRICE) AS MINPRICE,MAX(TOTALPRICE) AS MAXPRICE,
COUNT(*) AS ROWCOUNT_,SUM(TOTALPRICE) TOTALPRICE,AVG(TOTALPRICE) AS AVGPRICE
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE)
--Group by yöntemiyle grupladýktan sonra order by ile toplam fiyata göre sýraladýk.

SELECT TOP 10 CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC
--En çok satýþ yapan 10 þehri getirdik.

--SELECT CONVERT(DATE,DATE_) AS DATE2,* FROM SALES WHERE CITY = 'ANKARA'
--ORDER BY DATE_
--Buradaki Date tipi tarih ve saat türünde olduðu için dönüþüm yaptýk.
--Sadece tarih kýsmýný getirmiþ olduk.

SELECT * FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_

UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)
--Sales toblosu design ile deðiþtirdik ve oraya DATE2 isminde bir kolon ekledik.
--Bu kolonu update komutuyla güncelleyerek doldurduk.

SELECT * FROM SALES WHERE CITY='ANKARA'
AND DATE2='2019-01-01'
ORDER BY DATE_

SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2
--Eðer bir aggregate fonksiyonu kullanýyorsak
--group by yöntemini de kullanmamýz gerekli.

SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES 

WHERE DATE2='2019-01-01'

GROUP BY DATE2,CITY
ORDER BY DATE2,SUM(TOTALPRICE) DESC
--Burada günlere göre maðazalarýn satýþ performansý elde ettik.

--MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMLARINI GETÝRME
--Bu sefer bu yönteme göre sales tablosuna yeni bir kolon ekleyeceðiz.
SELECT * FROM SALES

SELECT DATEPART(MONTH,'2019-08-02')
--Bu komut bize herhangi bir tarih alanýnýn ay numarasýný gönderir.

UPDATE SALES SET MONTHNAME_='01.OCAK' WHERE DATEPART(MONTH,DATE2)=1
--Ocak ayý olanlar için tarih alaný ocak ayýna denk gelenleri
--01.OCAK ile update ediyorum.
UPDATE SALES SET MONTHNAME_='02.ÞUBAT' WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_='03.MART' WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_='04.NÝSAN' WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_='05.MAYIS' WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_='06.HAZÝRAN' WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_='07.TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_='08.AÐUSTOS' WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_='09.EYLÜL' WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_='10.EKÝM' WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_='11.KASIM' WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_='12.ARALIK' WHERE DATEPART(MONTH,DATE2)=12
--Bütün aylar için update komutunu kullandýk.

SELECT * FROM SALES

SELECT MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY MONTHNAME_
ORDER BY MONTHNAME_
--Aylara göre satýþ rakamlarýný elde edip sýraladýk.

SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_
--Þehirlerin aylara göre daðýlýmýný elde ettik.

SELECT MONTHNAME_,CITY,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY MONTHNAME_,CITY
--Aylarýn þehirlere göre satýþýný elde ettik.

SELECT MONTHNAME_,CITY,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY MONTHNAME_,SUM(TOTALPRICE) DESC
--Aylara göre en çok satýþ yapan þehirleri elde ettik.

--ÜRÜN KATEGORÝLERÝNE GÖRE SATIÞ RAKAMLARINI GETÝRME
SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT
FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4

--MAÐAZALARIN MÜÞTERÝ SAYISINI GETÝRME
SELECT CITY,FICHENO,COUNT(*)
FROM SALES WHERE MONTHNAME_='01.OCAK'
AND CITY='ADANA'
GROUP BY CITY,FICHENO
--Maðaza bazlý gerçek müþteri sayýsý Adana þehri için.
SELECT CITY,COUNT(DISTINCT FICHENO),COUNT(*)
FROM SALES WHERE MONTHNAME_='01.OCAK'

GROUP BY CITY
ORDER BY CITY
--Tüm þehirler için baktýk.Burada FICHENO'yu DISTINCT komutuyla tekilleþtirdik.
--Çünkü gerçek müþteri sayýsýný elde etmek istedik.Ayný fiþ no üzerinden birden
--fazla kez alýþveriþ yapýlmýþ.

SELECT CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) AS CUSTOMERCOUNT,
COUNT(*) AS ITEMCOUNT
FROM SALES WHERE MONTHNAME_='01.OCAK'
GROUP BY CITY
ORDER BY CITY

--BELLÝ BÝR CÝRONUN ÜZERÝNDE SATIÞ YAPAN MAÐAZALARI GETÝRME
SELECT CITY,SUM(TOTALPRICE)
FROM SALES

GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC
--Cirolarýna göre þehirlerimi getirdik.

SELECT CITY,SUM(TOTALPRICE)
FROM SALES

GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE) DESC
--Bir aggregate fonksiyonunu where þartý içinde kullanamazsýn.Bu yüzden burada
--HAVING yöntemini kullanacaðýz.Toplam satýþý 40000 üzerinde olanlarý getireceðiz.

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT
FROM SALES

GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE) DESC
--Cirosu 40000'den büyük olan seçtiðimiz þehirleri getirdik.

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>2000
ORDER BY SUM(TOTALPRICE) DESC
--2000'DEN FAZLA TEKÝL MÜÞTERÝSÝ OLANLARI GETÝRDÝK.

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>500
AND SUM(TOTALPRICE)>300000
ORDER BY SUM(TOTALPRICE) DESC
--Tekil müþteri sayýsý 500'den büyük ve Toplam satýþý 300000'den büyük olanlarý
--getirdi.

