SELECT * FROM COUNTRIES

SELECT * FROM CITIES

SELECT * FROM TOWNS

SELECT * FROM DISTRICTS

SELECT * FROM USERS WHERE ID=1

SELECT * FROM ADDRESS WHERE USERID=1
--ÝKÝ TABLOYU BÝRLEÞTÝRME
SELECT USERS.*,ADDRESS.ADDRESSTEXT FROM 

USERS,ADDRESS

WHERE USERS.ID=ADDRESS.USERID AND USERS.ID=1

SELECT USERS.NAMESURNAME,USERS.EMAÝL,
USERS.GENDER,USERS.BIRTHDATE,
ADDRESS.ADDRESSTEXT FROM 

USERS,ADDRESS
WHERE USERS.ID=ADDRESS.USERID AND USERS.ID=4

--ALÝAS KULLANIMI
SELECT U.NAMESURNAME,U.EMAÝL,
U.GENDER,U.BIRTHDATE,
A.ADDRESSTEXT FROM 
USERS U,ADDRESS A 
WHERE U.ID=A.USERID AND U.ID=4
--Diðer türlü yazýmýz kalabalýklaþýyor ve çirkinleþiyordu.Ama bu yöntemle kolon
--isimleri daha düzgün ve kýsa yazýlmýþ oluyor.

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAÝL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
A.ADDRESSTEXT ACIKADRES FROM 
USERS U,ADDRESS A 
WHERE U.ID=A.USERID AND U.ID=4
--Alias kullanýrken kolon isimlerini de deðiþtirebiliriz.

--ÝKÝDEN FAZLA TABLO ÇALIÞMA

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAÝL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY AS ULKE,CT.CITY AS SEHÝR,
T.TOWN AS ILCE,D.DISTRICT AS SEMT,
A.POSTALCODE AS POSTAKODU,
A.ADDRESSTEXT ACIKADRES FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
AND U.ID=4

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAÝL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY AS ULKE,CT.CITY AS SEHÝR,
T.TOWN AS ILCE,D.DISTRICT AS SEMT,
A.POSTALCODE AS POSTAKODU,
A.ADDRESSTEXT ACIKADRES FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
ORDER BY U.NAMESURNAME
--Bütün kullanýcýlarýn adreslerini getirdik.

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAÝL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY AS ULKE,CT.CITY AS SEHÝR,
T.TOWN AS ILCE,D.DISTRICT AS SEMT,
A.POSTALCODE AS POSTAKODU,
A.ADDRESSTEXT ACIKADRES FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
AND CT.CITY LIKE 'ÝZMÝR'
ORDER BY U.NAMESURNAME
--Adresi sadece Ýzmir olanlarý getirdik.

--AGGREGATE FONKSÝYONLARINI KULLANMA
SELECT COUNT(DISTINCT U.NAMESURNAME) FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID

SELECT DISTINCT U.NAMESURNAME FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
--Ayný yöntemi group by ile de yapabiliriz.

SELECT 
U.NAMESURNAME,COUNT(A.ID) AS ADRESSAYISI,COUNT(DISTINCT C.COUNTRY) AS ULKESAYISI,
COUNT(DISTINCT CT.ID) SEHIRSAYISI
FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
GROUP BY U.NAMESURNAME

SELECT 
U.NAMESURNAME,COUNT(A.ID) AS ADRESSAYISI,COUNT(DISTINCT C.COUNTRY) AS ULKESAYISI,
COUNT(DISTINCT CT.ID) SEHIRSAYISI
FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
GROUP BY U.NAMESURNAME
HAVING COUNT(A.ID)>2
--Ýkiden fazla adresi olanlarý HAVING yöntemiyle elde ettik.

SELECT 
CT.CITY,COUNT(U.ID) AS KULLANICISAYISI,
COUNT(DISTINCT D.DISTRICT) AS ILCESAYISI
FROM 
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
GROUP BY CT.CITY
--Þehirlere göre kullanýcý sayýsýný ve ilçe sayýsýný elde ettik.

--JOÝN UYGULAMALARI

SELECT U.NAMESURNAME,U.EMAÝL,
A.ADDRESSTEXT,
C.COUNTRY,CT.CITY,T.TOWN,D.DISTRICT
FROM 
USERS U JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID

SELECT CT.CITY,COUNT(U.ID) AS KULLANICISAYISI
FROM 
USERS U JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
GROUP BY CT.CITY
--GROUP BY YÖNTEMÝ ÝLE ÞEHÝRLERDEKÝ KULLANICI SAYISINI ELDE ETTÝK.




